
## INPUT
genomes: resources/test_data/genomes
annotations: resources/test_data/annotations

## OUTPUT
filtered_genomes: results/genomes_filtered
filtered_annotations: results/annotations_filtered
proteins: results/proteins
functions_interproscan: results/functions_interproscan
functions_eggnog: results/functions_eggnog
statistics: results/statistics
metadata: results/metadata

## PARAMETERS
min_len: 1000
orf_size: 30
